# Generated by Django 4.0.10 on 2023-04-22 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='unique name of category', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creation_user_id', models.IntegerField(blank=True, null=True)),
                ('update_user_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='unique name of product', max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creation_user_id', models.IntegerField(blank=True, null=True)),
                ('update_user_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParamValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='unique name of product', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creation_user_id', models.IntegerField(blank=True, null=True)),
                ('update_user_id', models.IntegerField(blank=True, null=True)),
                ('types', models.IntegerField(blank=True, choices=[(0, 'text'), (1, 'range')], default=0, help_text='type of range', null=True)),
                ('string_value', models.CharField(blank=True, max_length=100, null=True)),
                ('range_value', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='unique name of product', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creation_user_id', models.IntegerField(blank=True, null=True)),
                ('update_user_id', models.IntegerField(blank=True, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Patch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='unique name of product', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creation_user_id', models.IntegerField(blank=True, null=True)),
                ('update_user_id', models.IntegerField(blank=True, null=True)),
                ('parameters', models.ManyToManyField(related_name='patch_paramters', to='core.parameters')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_patch', to='core.products')),
                ('value', models.ManyToManyField(related_name='patch_value', to='core.paramvalues')),
            ],
        ),
        migrations.AddField(
            model_name='parameters',
            name='values',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_valu', to='core.paramvalues'),
        ),
        migrations.AddField(
            model_name='category',
            name='parameters',
            field=models.ManyToManyField(related_name='cat_paramters', to='core.parameters'),
        ),
    ]
