# Generated by Django 4.0.10 on 2023-04-29 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_parameters_paramvalues_products_patch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='creation_user_id',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='creation_user_id',
        ),
        migrations.RemoveField(
            model_name='paramvalues',
            name='creation_user_id',
        ),
        migrations.RemoveField(
            model_name='patch',
            name='creation_user_id',
        ),
        migrations.RemoveField(
            model_name='products',
            name='creation_user_id',
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parameters',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paramvalues',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patch',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
