# Generated by Django 4.0.10 on 2023-04-29 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_category_creation_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameters',
            name='values',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='param_valu', to='core.paramvalues'),
        ),
    ]
