# Generated by Django 4.0.10 on 2023-04-29 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_parameters_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parameters',
            field=models.ManyToManyField(blank=True, null=True, related_name='cat_paramters', to='core.parameters'),
        ),
    ]
