# Generated by Django 4.0.10 on 2023-04-29 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_parameters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='parameters',
            field=models.ManyToManyField(blank=True, null=True, related_name='patch_paramters', to='core.parameters'),
        ),
        migrations.AlterField(
            model_name='patch',
            name='value',
            field=models.ManyToManyField(blank=True, null=True, related_name='patch_value', to='core.paramvalues'),
        ),
    ]
